In [1]:
import torch
import numpy as np

In [2]:
data = [[1,2],[3,4]]
x_data = torch.tensor(data)

In [3]:
np_array = np.array(data)
x_np = torch.from_numpy(np_array)

In [4]:
torch.ones_like(x_data)

tensor([[1, 1],
        [1, 1]])

In [5]:
torch.rand_like(x_data, dtype = torch.float)

tensor([[0.0746, 0.9768],
        [0.4859, 0.8287]])

In [6]:
shape = (2,3)
rand_tensor = torch.rand(shape)

In [7]:
rand_tensor

tensor([[0.6717, 0.2920, 0.7335],
        [0.3711, 0.2121, 0.8149]])

In [9]:
tensor = torch.rand(3,4)

In [10]:
if torch.cuda.is_available():
  tensor = tensor.to('cuda')
  print(f"Device tensor is stored on: {tensor.device}")

Device tensor is stored on: cuda:0


In [11]:
tensor = torch.ones(4,4)
tensor[:,1] = 0
print(tensor)

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


In [15]:
t1 = torch.cat([tensor, tensor, tensor], dim=1)
print(t1)

tensor([[1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.]])


## Neural Network

In [18]:
import torch
from torchvision.models import resnet18, ResNet18_Weights
model = resnet18(weights=ResNet18_Weights.DEFAULT)
data = torch.rand(1,3,64,64)
labels = torch.rand(1,1000)


In [21]:
prediction = model(data)

In [22]:
loss = (prediction-labels).sum()

In [24]:
loss.backward()

In [26]:
optim  = torch.optim.SGD(model.parameters(), lr=1e-2,momentum=0.9)

In [27]:
optim.step()